### ISSUE TITLE
Bridge - function calls need to check for a proper response

### ISSUE THREAD

**Issue by DavidVanDrei** [willjallen/FactorioAgent#6]
Bridge.py step function should call a function and raise any errors it gets outputted.
Now it just checks that the status is 200...

How can we readout errors or successes the functions return?
```
        res = self.client.run(f"/c remote.call('scripts', 'load_script', 1, '{name}', '{code}'")

        if res.status_code != 200:
            raise RuntimeError("Failed to step Factorio server")
        returned_data = res.json()
        return json.loads(returned_data)
```

**Comment by willjallen** [comment]
https://github.com/willjallen/FactorioAgent/commit/97542621ae5fd115642307bc2c4ef03c33fa391b
